### ISSUE TITLE
无法加载任何模型

### ISSUE THREAD

**Issue by GengGode** [NaruseMioShirakana/MioTTS#4]
当前的Release版本，下载后同时去下载了三个模型，并解压到了Mods文件夹
![image](https://user-images.githubusercontent.com/47711102/203992212-292b9186-80c2-4a62-8be9-ed1ea1164641.png)

打开exe不弹窗报错，但是模型列表为空，仅显示 未选中
![image](https://user-images.githubusercontent.com/47711102/203992242-69ffeeec-3b91-4aad-a6c0-a7260fb1dc64.png)
// ====
经查看.mod文件，发现与readme不符，
![image](https://user-images.githubusercontent.com/47711102/203992449-974d1d9e-5303-4bfb-b15c-e7637e9258ea.png)
将 Mdid 修改为 Folder 后重试，依旧无法加载，请问怎么才能运行呢

**Comment by NaruseMioShirakana** [comment]
模型的配置文件现在已经完全改动了，每一个参数的标记都改了，详细的可以看readme

**Comment by GengGode** [comment]
感谢讲解，已经解决了
